import { Device, Agent, Skill, Activity, Session } from "./types";

export const devices: Device[] = [
  {
    id: "dev-macbook",
    name: "MacBook Pro M4",
    hostname: "mr-mbp",
    platform: "macOS",
    ip: "192.168.1.10",
    status: "online",
    lastSeen: new Date().toISOString(),
    createdAt: "2025-01-15T00:00:00Z",
  },
  {
    id: "dev-kuro",
    name: "Kuro (VPS)",
    hostname: "kuro.openclaw.io",
    platform: "Linux",
    ip: "163.44.xxx.xxx",
    status: "online",
    lastSeen: new Date().toISOString(),
    createdAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "dev-kon",
    name: "Kon (VPS)",
    hostname: "kon.openclaw.io",
    platform: "Linux",
    ip: "160.16.xxx.xxx",
    status: "online",
    lastSeen: new Date().toISOString(),
    createdAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "dev-ao",
    name: "Ao (VPS)",
    hostname: "ao.openclaw.io",
    platform: "Linux",
    ip: "133.18.xxx.xxx",
    status: "degraded",
    lastSeen: "2026-05-02T15:00:00Z",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "dev-pixel",
    name: "Pixel 9",
    hostname: "pixel9",
    platform: "Android",
    status: "online",
    lastSeen: new Date().toISOString(),
    createdAt: "2025-11-01T00:00:00Z",
  },
];

export const skills: Skill[] = [
  { id: "sk-gog", name: "gog", description: "Google Workspace CLI (Gmail, Calendar, Drive, Sheets)", category: "integration" },
  { id: "sk-github", name: "github", description: "GitHub issues, PRs, CI/CD management", category: "integration" },
  { id: "sk-coding", name: "coding-agent", description: "Delegate coding tasks to sub-agents", category: "development" },
  { id: "sk-gemini", name: "gemini", description: "Gemini CLI for Q&A and generation", category: "ai" },
  { id: "sk-weather", name: "weather", description: "Weather forecasts and conditions", category: "utility" },
  { id: "sk-obsidian", name: "obsidian", description: "Obsidian vault management", category: "productivity" },
  { id: "sk-ads", name: "ads-meta", description: "Meta Ads analysis and monitoring", category: "marketing" },
  { id: "sk-health", name: "healthcheck", description: "Host security audit and hardening", category: "ops" },
  { id: "sk-tmux", name: "tmux", description: "Remote tmux session control", category: "ops" },
  { id: "sk-skill", name: "skill-creator", description: "Create and manage AgentSkills", category: "meta" },
  { id: "sk-discord", name: "discord", description: "Discord channel access and messaging", category: "integration" },
  { id: "sk-whisper", name: "openai-whisper", description: "Local speech-to-text with Whisper", category: "ai" },
];

export const agents: Agent[] = [
  {
    id: "ag-openclaw-main",
    name: "OpenClaw Main",
    type: "orchestrator",
    llm: "claude-opus-4-6",
    status: "active",
    description: "Primary orchestrator — heartbeat monitoring, email checks, task delegation, ad monitoring",
    deviceId: "dev-macbook",
    skillIds: ["sk-gog", "sk-github", "sk-coding", "sk-obsidian", "sk-ads", "sk-skill", "sk-discord"],
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "ag-codex",
    name: "Codex Worker",
    type: "coder",
    llm: "codex-1",
    status: "idle",
    description: "Background coding agent for feature development, PR creation, and code review",
    deviceId: "dev-macbook",
    skillIds: ["sk-github", "sk-coding"],
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "ag-kuro",
    name: "Kuro Gateway",
    type: "gateway",
    llm: "claude-sonnet-4-6",
    status: "active",
    description: "VPS gateway — Telegram relay, message routing, webhook handling",
    deviceId: "dev-kuro",
    skillIds: ["sk-health", "sk-tmux"],
    createdAt: "2025-06-15T00:00:00Z",
  },
  {
    id: "ag-kon",
    name: "Kon Gateway",
    type: "gateway",
    llm: "claude-sonnet-4-6",
    status: "active",
    description: "Secondary VPS gateway for redundancy and failover",
    deviceId: "dev-kon",
    skillIds: ["sk-health", "sk-tmux"],
    createdAt: "2025-06-15T00:00:00Z",
  },
  {
    id: "ag-ao",
    name: "Ao Monitor",
    type: "monitor",
    llm: "claude-haiku-4-5",
    status: "error",
    description: "Monitoring agent — currently degraded due to connectivity issues",
    deviceId: "dev-ao",
    skillIds: ["sk-health"],
    createdAt: "2025-09-15T00:00:00Z",
  },
  {
    id: "ag-mobile",
    name: "Mobile Assistant",
    type: "assistant",
    llm: "claude-haiku-4-5",
    status: "idle",
    description: "Lightweight mobile agent for quick queries via Telegram",
    deviceId: "dev-pixel",
    skillIds: ["sk-gemini", "sk-weather", "sk-whisper"],
    createdAt: "2025-11-15T00:00:00Z",
  },
];

export const activities: Activity[] = [
  { id: "act-1", agentId: "ag-openclaw-main", type: "email-check", summary: "朝メールチェック — 5アカウントスキャン、新着2件（Studio Inc支払失敗、JFR赤井面談）", status: "completed", duration: 45, createdAt: "2026-05-03T08:27:00+09:00" },
  { id: "act-2", agentId: "ag-openclaw-main", type: "email-check", summary: "昼メールチェック — GCP請求書、DHL請求書、Bitly通知検出", status: "completed", duration: 38, createdAt: "2026-05-02T12:08:00+09:00" },
  { id: "act-3", agentId: "ag-openclaw-main", type: "ad-monitor", summary: "KATAOMOI広告チェック — Meta APIトークン期限切れ (error 190)", status: "error", duration: 12, createdAt: "2026-05-02T21:30:00+09:00" },
  { id: "act-4", agentId: "ag-openclaw-main", type: "heartbeat", summary: "HEARTBEAT_OK — スケジュールタスクなし", status: "completed", duration: 1, createdAt: "2026-05-03T07:57:00+09:00" },
  { id: "act-5", agentId: "ag-openclaw-main", type: "development", summary: "agent-hubプロジェクト構築開始 — Next.js + Tailwind", status: "in_progress", duration: 600, createdAt: "2026-05-03T08:35:00+09:00" },
  { id: "act-6", agentId: "ag-codex", type: "coding", summary: "second-brainカンバンボードの実装", status: "completed", duration: 1800, createdAt: "2026-04-20T14:00:00+09:00" },
  { id: "act-7", agentId: "ag-codex", type: "pr-review", summary: "PR #12 コードレビュー — personaplex-demo改善", status: "completed", duration: 300, createdAt: "2026-04-22T10:00:00+09:00" },
  { id: "act-8", agentId: "ag-kuro", type: "relay", summary: "Telegram ↔ CLI メッセージリレー 284件", status: "completed", duration: 86400, createdAt: "2026-05-02T00:00:00+09:00" },
  { id: "act-9", agentId: "ag-kuro", type: "healthcheck", summary: "システム正常 — CPU 8%, Memory 42%, Disk 31%", status: "completed", duration: 5, createdAt: "2026-05-03T06:00:00+09:00" },
  { id: "act-10", agentId: "ag-kon", type: "relay", summary: "フェイルオーバー待機 — リレー0件", status: "completed", duration: 86400, createdAt: "2026-05-02T00:00:00+09:00" },
  { id: "act-11", agentId: "ag-ao", type: "healthcheck", summary: "接続タイムアウト — ヘルスチェック失敗", status: "error", duration: 30, createdAt: "2026-05-02T15:00:00+09:00" },
  { id: "act-12", agentId: "ag-mobile", type: "query", summary: "東京の天気照会 — 晴れ 22°C", status: "completed", duration: 3, createdAt: "2026-05-02T07:30:00+09:00" },
  { id: "act-13", agentId: "ag-openclaw-main", type: "email-check", summary: "夕方メールチェック — 全5アカウント確認、新着3件", status: "completed", duration: 42, createdAt: "2026-05-01T18:30:00+09:00" },
  { id: "act-14", agentId: "ag-codex", type: "coding", summary: "proactive-coder CLIツール実装", status: "completed", duration: 2400, createdAt: "2026-04-18T09:00:00+09:00" },
  { id: "act-15", agentId: "ag-kuro", type: "webhook", summary: "GitHub webhook受信 — push event 3件処理", status: "completed", duration: 8, createdAt: "2026-05-01T14:00:00+09:00" },
];

export const sessions: Session[] = [
  { id: "ses-1", agentId: "ag-openclaw-main", startedAt: "2026-05-03T00:00:00+09:00", status: "active", tokenUsed: 385000, messages: 124 },
  { id: "ses-2", agentId: "ag-codex", startedAt: "2026-05-02T14:00:00+09:00", endedAt: "2026-05-02T15:30:00+09:00", status: "completed", tokenUsed: 210000, messages: 56 },
  { id: "ses-3", agentId: "ag-kuro", startedAt: "2026-05-01T00:00:00+09:00", status: "active", tokenUsed: 78000, messages: 284 },
  { id: "ses-4", agentId: "ag-kon", startedAt: "2026-05-01T00:00:00+09:00", status: "active", tokenUsed: 12000, messages: 18 },
  { id: "ses-5", agentId: "ag-ao", startedAt: "2026-05-02T12:00:00+09:00", endedAt: "2026-05-02T15:00:00+09:00", status: "error", tokenUsed: 5400, messages: 7 },
  { id: "ses-6", agentId: "ag-mobile", startedAt: "2026-05-02T07:00:00+09:00", endedAt: "2026-05-02T07:35:00+09:00", status: "completed", tokenUsed: 3200, messages: 4 },
];
